---
- name: disable ctrl-alt-del
  become: 'yes'
  systemd:
    name: ctrl-alt-del.target
    masked: 'yes'
    enabled: 'no'
    state: stopped
  tags:
    - ctrl-alt-del
    - systemd
    - CCE-80785-9
...
