---
- name: reboot if required
  become: 'yes'
  setup: ~
  notify:
    - reboot node
  when: ansible_distribution == "Ubuntu" and ansible_local.reboot.required and
        reboot_ubuntu
  tags:
    - reboot
    - ubuntu
...
