---
- name: remove /tmp from fstab
  become: 'yes'
  mount:
    path: /tmp
    state: absent
  tags:
    - fstab

- name: remove floppy from fstab
  become: 'yes'
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^(.*)floppy(.*)$'
  tags:
    - fstab
...
