---
- name: register /etc/default/motd-news
  stat:
    path: /etc/default/motd-news
  register: motd_news
  tags:
    - motd

- name: disable motd-news
  become: 'yes'
  lineinfile:
    regexp: "^ENABLED="
    line: "ENABLED=0"
    dest: /etc/default/motd-news
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  notify:
    - mask motdnews timer
    - mask motdnews service
  when: ansible_os_family == "Debian" and motd_news.stat.exists
  tags:
    - motd

- name: find update-motd.d files
  become: 'yes'
  find:
    paths: /etc/update-motd.d
    file_type: file
  register: update_motd_permissions
  tags:
    - motd

- name: motd updates permissions
  become: 'yes'
  file:
    dest: "{{ item.path }}"
    mode: 0444
  with_items:
    - "{{ update_motd_permissions.files }}"
  when: ansible_os_family == "Debian"
  tags:
    - motd

- name: /etc/update-motd.d permission
  become: 'yes'
  file:
    dest: /etc/update-motd.d
    mode: 0755
  when: ansible_os_family == "Debian"
  tags:
    - motd
...
